In [1]:
import numpy as np
import os
import pydicom
import pandas
import matplotlib.pyplot as plt
import normalize
import scipy.ndimage
import SimpleITK as sitk
import datasets
from sklearn.model_selection import train_test_split 


In [10]:
path_t2_tra_np = './Data/t2_tra_np/False FID 1 ProstateX-0001 IJK [157 186  10] DCM 6.npy'
a = np.load(path_t2_tra_np)

In [11]:
a.shape

(1, 24, 24)

In [12]:
coords = [157,186,10]
coords

[157, 186, 10]

In [13]:
a = a[coords[2]-2:coords[2]+3, coords[1]-25:coords[1]+25, coords[0]-25:coords[0]+25]
a.shape

(0, 0, 0)

In [14]:
a.shape[0]

0

In [15]:
b = np.array([0,1,2,3,4,5,6])

In [16]:
get = 6
size = 3

In [17]:
b[get - size // 2 : (get + size // 2) + 1]

array([5, 6])

In [18]:
def extract(arr, ind, size):
    check_bot = ind - size // 2 
    check_top = (ind + size // 2) + 1
    over_top = 0
    over_bot = 0
    if check_bot < 0:
        over_bot = abs(check_bot)   
    elif check_top > len(arr):
        over_top = check_top - len(arr)
    print("bot: {}, top: {}\n".format(check_bot, check_top))
    print("over_bot: {}, over_top: {}\n".format(over_bot, over_top))

    ext = arr[(ind - size // 2) + over_bot - over_top: ((ind + size // 2) + 1) - over_top + over_bot]
    return ext

In [19]:
len(b)

7

In [20]:
b.shape

(7,)

In [21]:
b.shape

(7,)

In [22]:
b[0:7]

array([0, 1, 2, 3, 4, 5, 6])

In [23]:
extract(b, 6, 3)

bot: 5, top: 8

over_bot: 0, over_top: 1



array([4, 5, 6])

In [24]:
np.load('./Data/t2_tra_np_3D_min_max/False FID 1 ProstateX-0001 IJK [157 186  10] DCM 6.npy').mean()

-0.3885431

In [25]:
list1 = ['a1','b1','c1','d1','e1']


In [26]:
for i in range(len(list1)):
    j = i
    while j < len(list1):
        print(list1.__getitem__(i) + list1.__getitem__(j))
        j = j + 1

a1a1
a1b1
a1c1
a1d1
a1e1
b1b1
b1c1
b1d1
b1e1
c1c1
c1d1
c1e1
d1d1
d1e1
e1e1


In [27]:
def get_pair_label(label1, label2):
    if label1 == label2:
        return 1
    else:
        return 0

In [28]:
a = np.array([0,1,0,1])
b = np.array([0,1,1,0])

In [14]:
path_t2_tra_np_min_max = './Data/t2_tra_np_min_max'
images = os.listdir(path_t2_tra_np_min_max)
train, test = train_test_split(images, test_size=0.2)
train = train[0:3]
train


['False FID 3 ProstateX-0144 IJK [193 196   7] DCM 4.npy',
 'False FID 2 ProstateX-0099 IJK [147 231  11] DCM 5.npy',
 'False FID 2 ProstateX-0149 IJK [172 236   9] DCM 9.npy']

In [36]:
train_dataset = datasets.SiameseDataset(path_t2_tra_np_min_max, train)
train_dataset.change_strategy(get_pair=False)

In [37]:
len(train_dataset)

3

In [24]:
train_iter = iter(train_dataset)

In [34]:
train_iter.__next__()

StopIteration: 

In [27]:
train_dataset.change_strategy(get_pair=True)

In [1]:
a = 5

In [2]:
for i in a:
    print(i)

TypeError: 'int' object is not iterable